### ISSUE TITLE
Version 0.19.0 introduces breaking changes

### ISSUE THREAD

**Issue by Gavisann** [frenck/python-wled#1417]
# Problem/Motivation

Version `0.19.0` introduces breaking changes and is not backwards compatible with older versions of WLED. I'm noticing this now as the package requirements have been updated in the latest beta release of Home Assistant `2024.8.0b1`.

## Expected behavior

Minor patch versions should be backwards compatible. The latest version of python-wled, currently `0.20.0` should work with past versions of the WLED project.

## Actual behavior

Older versions of WLED (currently testing with 0.10.0) no longer work with versions `0.19.0` of python-wled.

## Steps to reproduce

Use python3.12 and install the latest version of python-wled via pip. 

Attempt to run the example code in the README and you will see the following error:
```
Traceback (most recent call last):
  File "/whale/docs/projects/Python/wled/wled-test/app.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/whale/docs/projects/Python/wled/wled-test/app.py", line 9, in main
    device = await led.update()
             ^^^^^^^^^^^^^^^^^^
  File "/whale/docs/projects/Python/wled/python-wled/wled-venv/lib64/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whale/docs/projects/Python/wled/python-wled/wled-venv/lib64/python3.12/site-packages/wled/wled.py", line 259, in update
    if not (presets := await self.request("/presets.json")):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whale/docs/projects/Python/wled/python-wled/wled-venv/lib64/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whale/docs/projects/Python/wled/python-wled/wled-venv/lib64/python3.12/site-packages/wled/wled.py", line 205, in request
    raise WLEDError(
wled.exceptions.WLEDError: (404, {'message': 'Not Found'})
```
Preform the same test with python-wled version `0.18.0` and I get the expected output of:
```
0.10.0
```
## Proposed changes

I think it would be best to move these breaking changes to 1.0.0 and have 0.18.0 be the last version that supports older versions of WLED. Thoughts?

**Comment by frenck** [comment]
> Minor patch versions should be backwards compatible.

Incorrect. Semver below version 1, the minors may contain breaking changes.

**Comment by frenck** [comment]
> Older versions of WLED (currently testing with 0.10.0) no longer work with versions 0.19.0 of python-wled.

Correct, as upstream Home Assistant will list, you'd need at least version 0.14.0 of WLED.

Also listed in the release notes of v0.19.0:

https://github.com/frenck/python-wled/releases/tag/v0.19.0

../Frenck
