### ISSUE TITLE
Test code has no method "light"

### ISSUE THREAD

**Issue by nickolas1969** [frenck/python-wled#490]
I copied the example code to a file, and ran it. It pulled the version, but bailed turning on the WLED module.
using WLED 0.13.0-b5, python 3.10.0

```py
import asyncio

from wled import WLED


async def main():
    """Show example on controlling your WLED device."""
    async with WLED("10.0.0.47") as led:
        device = await led.update()
        print(device.info.version)

        # Turn strip on, full brightness
        await led.light(on=True, brightness=255)


if __name__ == "__main__":
    asyncio.run(main())
```

```ps
PS C:\Users\nicko\OneDrive\Documents\Repos\nellson\nellson> python .\wled-test.py
0.13.0-b5
Traceback (most recent call last):
  File "C:\Users\nicko\OneDrive\Documents\Repos\nellson\nellson\wled-test.py", line 17, in <module>
    asyncio.run(main())
  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\nicko\OneDrive\Documents\Repos\nellson\nellson\wled-test.py", line 13, in main
    await led.light(on=True, brightness=255)
AttributeError: 'WLED' object has no attribute 'light'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000214AF0672E0>
Traceback (most recent call last):
  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
PS C:\Users\nicko\OneDrive\Documents\Repos\nellson\nellson>
```

**Comment by frenck** [comment]
Oh that is a very very very outdated example in the README.... Oops 🤦‍♂️ 

Will adjust it.

**Comment by frenck** [comment]
PR #495 fixes the example.

Replace `light` with `master`, that will do the trick :)

Sorry about that 🙏

**Comment by nickolas1969** [comment]
LOL, that happens 😃

 

Thank you! Is there a list of methods available? 

 

Nick

**Comment by frenck** [comment]
Open the files :) all methods are inline documented

**Comment by nickolas1969** [comment]
Sorry, missed that 😃

 

Swapping in “master” for “light” worked, but it’s still dropping an exception at end of run.  Lights came on nice and bright.

 

PS C:\Users\nicko\OneDrive\Documents\Repos\nellson\nellson> python .\wled-test.py

0.13.0-b5

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001FCEC1272E0>

Traceback (most recent call last):

  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__

    self.close()

  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close

    self._loop.call_soon(self._call_connection_lost, None)

  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon

    self._check_closed()

  File "C:\Users\nicko\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed

    raise RuntimeError('Event loop is closed')

RuntimeError: Event loop is closed
